import Head from 'next/head';
import Image from 'next/image';

import QA from '../components/QandA';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mind Connector</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <h1>Home</h1>

        <QA />
      </div>
    </>
  );
}
